### ISSUE TITLE
purpleprint.png has no Artist metadata

### ISSUE THREAD

**Issue by codygarver** [elementary/prerelease-settings#3]
For the Desktop plug feature.

**Comment by anddam** [comment]
Should this be @cassidyjames's?

**Comment by codygarver** [comment]
The wallpaper artist credit is supposed to be `Daniel Fore` but the file seems to be corrupt so adding metadata still doesn't let `exif` or the Wallpaper System Settings feature show the tooltip.

**Comment by N00byKing** [comment]
IIRC PNG doesn't work with the `exif` command as PNG files don't store Exif data, and JPEGs do. You *can* save metadata in PNGs though, but it won't be readable by `exif`, by using things like `exiftool`.

For Example:
```
**@**:~/Desktop/Git/prerelease-settings/backgrounds$ exif --create-exif purpleprint.png
Corrupt data
The data provided does not follow the specification.
jpeg-data: Data does not follow JPEG specification.
```
^ This implies what I just said, and happens when you instruct `exif` to create metadata by itself by using `--create-exif`. But, as it says, it only works with JPEGs.

Might be wrong though

**Comment by anddam** [comment]
Given that PNG doesn't support Exif and that the [plug tooltip feature](https://github.com/elementary/switchboard-plug-pantheon-shell/blob/master/src/Widgets/WallpaperContainer.vala#L172) handles errors in Exif parsing or an missing Artist metadata already, Is this a blocking issue at all?

**Comment by m0eter** [comment]
Or use an LZW compressed TIFF. TIFF actually supports EXIF, though you might want to use exiftool to set/read them, not exif.

**Comment by deyvisonrocha** [comment]
I was able to add the artist information. I can not test now.

I installed exiftool (libimage-exiftool-perl) and executed the following command:
exiftool -artist = "Daniel Foré" purpleprint.png

And I got the data according to the prints.

![captura de tela de 2018-06-06 20-45-42](https://user-images.githubusercontent.com/686067/41071094-a2e07956-69cc-11e8-9a66-74ffa4e05831.png)
![captura de tela de 2018-06-06 20-48-05](https://user-images.githubusercontent.com/686067/41071109-b22f0cc4-69cc-11e8-84fb-2fd4d6a47450.png)

**Comment by kollienne** [comment]
Apparently [as of July 2017](http://ftp-osl.osuosl.org/pub/libpng/documents/pngext-1.5.0.html#C.eXIf) png does now support Exif data. [exiftool 10.59 or later](https://stackoverflow.com/questions/9542359/does-png-contain-exif-data-like-jpg/24916466#24916466) should work.
