### ISSUE TITLE
[Request] Purpleprint wallpaper version-agnostic and/or source file

### ISSUE THREAD

**Issue by peterlewis** [elementary/prerelease-settings#8]
**Firstly, a big thank you to @danrabbit for making such a wonderful wallpaper that has stood the test of time and my taste and remains my elementary OS wallpaper!**

## Problem

The problem is that I ❤️ @danrabbit's [purpleprint.png](https://github.com/elementary/prerelease-settings/blob/master/backgrounds/purpleprint.png) but it still says `5.0 "JUNO" BETA`.

## Proposal

It's no biggie, I enjoy living the retro life, but if it was at all possible, I would thoroughly appreciate it if @danrabbit was able to provide either a version-agnostic release of `purpleprint.png` or the source file for the image, so that people could amend themselves.

## Prior Art

The current version of `purpleprint.png` can be found at:

https://github.com/elementary/prerelease-settings/blob/master/backgrounds/purpleprint.png

**Comment by cassidyjames** [comment]
It's available here: 

https://github.com/elementary/mockups/blob/28978fbb9f090e338061e29db68611994d02b010/developer_wall.svg 

:)

**Comment by peterlewis** [comment]
> It's available here:
> 
> https://github.com/elementary/mockups/blob/28978fbb9f090e338061e29db68611994d02b010/developer_wall.svg
> 
> :)

Ah! It was right in front my nose this entire time! Thank you so much for pointing that out @cassidyjames and thank you again @danrabbit for the wallpaper!
